# Taken from osqp-python

name: Build Wheels

on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  pull_request:
    branches: [main]

jobs:
  build_sdist:
    name: Build source
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
        with:
          submodules: "recursive"

      - name: Build source and wheel
        run: |
          python -m pip install build
          python -m build --outdir=wheelhouse

      - name: Upload sdist and wheel to github
        uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: wheelhouse/*
          if-no-files-found: error
